# Site settings
author: Derek Cerretani
title: ReadMe
header-img: img/home-bg.png
email: derekcerretani@gmail.com
copyright_name: Derek Cerretani
description: > # this means to ignore newlines until "baseurl:"
  A Collection of Lessons Learned
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  drkjc

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
